language: python
python:
  - "3.4"
  - "2.7"
env:
  - DJANGO=1.7.8
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements-tests.txt --use-mirrors
  - pip install coveralls
  - pip install flake8
before_script:
  flake8 .
script:
  - coverage run --source=basic_site setup.py test
after_success:
  - coveralls
